version: '3.5'

services:
  twit:
    build: app
    command: yarn build-test
    # command: node_modules/.bin/nodemon server.js
    # ports:
    #     - '3000:3000'
    #     - '3001:3001'
    volumes:
        - ./app:/home/app-user/app
        - /home/app-user/app/node_modules
    env_file:
      - .env
    environment:
      - CONSUMER_KEY
      - CONSUMER_SECRET
      - ACCESS_TOKEN
      - ACCESS_TOKEN_SECRET
